import { AthleteProfile, RaceDetails, Strategy, Brand, Testimonial } from '../types';

export const DEFAULT_ATHLETE: AthleteProfile = {
  weight: 70,
  age: 28,
  sex: 'M',
  vo2max: 55,
  experience: 'intermediate',
};

export const DEFAULT_RACE: RaceDetails = {
  distance: 50,
  elevationPos: 2500,
  elevationNeg: 2500,
  duration: 7,
  location: 'Chamonix',
};

export const DEFAULT_STRATEGY: Strategy = {
  refuels: 4,
  objective: 'Just finish',
};

export const BRANDS: Brand[] = [
  {
    id: 'maurten-320',
    category: 'carbs',
    brand: 'Maurten',
    name: 'Drink Mix 320',
    carbs: 80,
    kcal: 320,
    sodium: 500,
    rating: 4.9,
    link: 'https://www.maurten.com',
    description: 'Highest carb density on the market. Zero fiber, hydrogel tech for maximum absorption.',
    badge: 'Elite Choice',
  },
  {
    id: 'sis-beta-fuel',
    category: 'carbs',
    brand: 'Science in Sport',
    name: 'Beta Fuel Gel',
    carbs: 40,
    kcal: 160,
    sodium: 200,
    rating: 4.7,
    link: 'https://www.scienceinsport.com',
    description: '2:1 glucose-to-fructose ratio matching your dual-transporter target.',
    badge: 'Best Value',
  },
  {
    id: 'tailwind-endurance',
    category: 'carbs',
    brand: 'Tailwind Nutrition',
    name: 'Endurance Fuel',
    carbs: 50,
    kcal: 200,
    sodium: 303,
    rating: 4.8,
    link: 'https://www.tailwindnutrition.com',
    description: 'All-in-one: calories, electrolytes and hydration in a single mix. Gut-friendly.',
    badge: 'Ultra Favorite',
  },
  {
    id: 'naak-cookie',
    category: 'carbs',
    brand: 'Naak',
    name: 'Ultra Energy Cookie',
    carbs: 40,
    kcal: 200,
    sodium: 150,
    rating: 4.6,
    link: 'https://www.naak.com',
    description: 'Real-food energy. Easy to chew on technical descents. 40g carbs per cookie.',
    badge: 'Trail Favorite',
  },
  {
    id: 'liquid-iv',
    category: 'sodium',
    brand: 'Liquid IV',
    name: 'Hydration Multiplier',
    carbs: 11,
    kcal: 45,
    sodium: 500,
    rating: 4.7,
    link: 'https://www.liquid-iv.com',
    description: 'High-sodium electrolyte boost — ideal when temperatures climb above 20°C.',
    badge: 'Hot Weather Pick',
  },
  {
    id: 'nuun-sport',
    category: 'sodium',
    brand: 'Nuun',
    name: 'Sport Tablets',
    carbs: 2,
    kcal: 15,
    sodium: 300,
    rating: 4.5,
    link: 'https://www.nuunlife.com',
    description: 'Effervescent electrolyte tabs. Lightweight, easy to carry, drop in any flask.',
    badge: 'Budget Pick',
  },
  {
    id: 'gu-roctane',
    category: 'caffeine',
    brand: 'GU Energy',
    name: 'Roctane Energy Gel',
    carbs: 21,
    kcal: 100,
    sodium: 125,
    rating: 4.6,
    link: 'https://guenergy.com',
    description: '100mg caffeine plus amino acids — a clean mid-race energy boost.',
    badge: 'Caffeine Boost',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: 'Crushed my first UTMB with Delta-V. The refueling schedule was spot on the whole way.',
    name: '@ultrarunner_23',
    source: 'Strava',
    rating: 5,
    avatar: 'U',
    race: 'UTMB 170km',
  },
  {
    quote: 'Game changer. No more guessing on nutrition — the science is finally accessible.',
    name: '@trailblazer_99',
    source: 'Komoot',
    rating: 5,
    avatar: 'T',
    race: 'CCC 100km',
  },
  {
    quote: 'Finally a tool built by runners for runners. Used it for three races now.',
    name: '@endurance_king',
    source: 'Instagram',
    rating: 5,
    avatar: 'E',
    race: 'TDS 145km',
  },
  {
    quote: 'The weather adjustment is genius. Nailed my hydration through 28°C of full sun.',
    name: '@montagne_runner',
    source: 'Strava',
    rating: 5,
    avatar: 'M',
    race: 'OCC 55km',
  },
];
